/***************************************************************************************
* \file Chess.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef CHESS_H
#define CHESS_H

#include <stdint.h>

#define CHESS_NUM_INTENTS 1
#define CHESS_NUM_COMMANDS 84
#define CHESS_NUM_VARIABLES 3
#define CHESS_NUM_VARIABLE_PHRASES 14
#define CHESS_NUM_UNIT_PHRASES 16
#define CHESS_INTENT_MAP_ARRAY_TOTAL_SIZE 672
#define CHESS_UNIT_PHRASE_MAP_ARRAY_TOTAL_SIZE 252

extern const char* Chess_intent_name_list[CHESS_NUM_INTENTS];

extern const char* Chess_variable_name_list[CHESS_NUM_VARIABLES];

extern const char* Chess_variable_phrase_list[CHESS_NUM_VARIABLE_PHRASES];

extern const char* Chess_unit_phrase_list[CHESS_NUM_UNIT_PHRASES];

extern const int Chess_intent_map_array[CHESS_INTENT_MAP_ARRAY_TOTAL_SIZE];

extern const int Chess_intent_map_array_sizes[CHESS_NUM_COMMANDS];

extern const int Chess_variable_phrase_sizes[CHESS_NUM_VARIABLES];

extern const int Chess_unit_phrase_map_array[CHESS_UNIT_PHRASE_MAP_ARRAY_TOTAL_SIZE];

extern const int Chess_unit_phrase_map_array_sizes[CHESS_NUM_COMMANDS];

#endif // CHESS_H
