/***************************************************************************************
* \file Chess_U55_CMDmodel.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef CHESS_U55_CMDMODEL_H
#define CHESS_U55_CMDMODEL_H

extern const char Chess_CMDmodeldata[];
#define CHESS_CMDMODELDATA_SIZE 34196

#endif // CHESS_U55_CMDMODEL_H
