/***************************************************************************************
* \file Chess_U55_WWmodel.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef CHESS_U55_WWMODEL_H
#define CHESS_U55_WWMODEL_H

extern const char Chess_WWmodeldata[];
#define CHESS_WWMODELDATA_SIZE 7376

#endif // CHESS_U55_WWMODEL_H
